parent=keycloak.v2
import=common/keycloak

# keycloak.v2'nin kendi styles.css'ini + bizim override'imizi sırayla yükle.
# Sıra önemli: euroriente.css sonra geldigi icin ayni ozellikleri ezer.
styles=css/styles.css css/euroriente.css
